stages:
    - test
    - build

test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm test


build-image:
  # Use the official docker image.
  image: docker:latest
  stage: build
  only:
    - master
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker tag "$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" "$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest"
  
